# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # tags:
    #   - v*.*.*
    branches: [scholasticnepal]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    name: Build Image with docker
    runs-on: ubuntu-latest
    env:
      REPO: ashish336b/blsonepal
      DOCKERREPO: ashish336b/scholastic
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker hub
        run: docker login -u "${{secrets.USERNAME}}" -p "${{secrets.PASS}}"
      - name: Build Docker Image
        run: docker build --no-cache -t $DOCKERREPO .
      - name: Publish Docker image
        run: docker push $DOCKERREPO

  redeploy:
    name: Redeploy Webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        with:
          url: http://206.189.130.205:9000/hooks/scholastic

  notify:
    name: Send Success Message to Discord
    runs-on: ubuntu-latest
    needs: [redeploy]
    steps:
      - uses: actions/checkout@master
      - name: Send Default Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{secrets.DISCORD_ID}}
          webhook_token: ${{secrets.DISCORD_TOKEN}}
          message: Good Job ! `scholastic`  ${{ github.event_name }} has been deployed to server sucessfully !!
